openapi: 3.1.0
info:
  title: editor-api
  version: 1.0.0
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /edit_simulation/:
    post:
      summary: Edit Archive Simulation
      operationId: edit-simulation
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_edit-simulation'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulSimulationEditConfirmation'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /download/{file_identifier}:
    get:
      summary: Download Combine Archive
      description: Serve the edited COMBINE archive for download.
      operationId: download-archive
      parameters:
      - name: file_identifier
        in: path
        required: true
        schema:
          type: string
          title: File Identifier
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchiveDownloadResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ArchiveDownloadResponse:
      properties:
        path:
          type: string
          title: Path
        filename:
          type: string
          title: Filename
        media_type:
          type: string
          title: Media Type
      type: object
      required:
      - path
      - filename
      - media_type
      title: ArchiveDownloadResponse
    Body_edit-simulation:
      properties:
        archive:
          type: string
          format: binary
          title: Archive
        edit_request_str:
          type: string
          title: Edit Request Str
        new_omex_filename:
          type: string
          title: New Omex Filename
      type: object
      required:
      - archive
      - edit_request_str
      - new_omex_filename
      title: Body_edit-simulation
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    SuccessfulSimulationEditConfirmation:
      properties:
        message:
          type: string
          title: Message
          default: Simulation edited successfully.
        download_link:
          type: string
          title: Download Link
      type: object
      required:
      - download_link
      title: SuccessfulSimulationEditConfirmation
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
